### ISSUE TITLE
Installation did not succeed

### ISSUE THREAD

**Issue by nigatou** [nigatou/FirstAndroidStudio#1]
![Capture](https://user-images.githubusercontent.com/71267523/100499157-595c7480-3178-11eb-8e1d-81a6015f09b8.PNG)

Я ожидаю работающего приложения, но вместо этого получаю эту ошибку и пустой экран
Android 11,

**Comment by Vanya13331** [comment]
https://medium.com/@aedwin905/solved-failure-calling-service-package-broken-pipe-32-3b860c7e04bb

**Comment by nigatou** [comment]
nice
